/*
 * Copyright (c) 2015 Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <errno.h>

#include <arch/tsb/cdsi.h>
#include <arch/tsb/cdsi0_offs_def.h>
#include <arch/tsb/cdsi0_reg_def.h>
#include <arch/tsb/csi.h>

/**
 * @brief Set the registers in CSI controller to start transfer.
 * @param dev Pointer to the CDSI device
 * @param cfg Pointer to CSI transmitter configuration structure
 *
 * @return 0 on success or a negative error code on failure.
 */
int csi_tx_start(struct cdsi_dev *dev, struct csi_tx_config *cfg)
{
    uint32_t rdata;

    /* Set to Tx mode for CDSI */
    cdsi_write(dev, CDSI0_AL_TX_BRG_CDSITX_MODE_OFFS,
               CDSI0_AL_TX_BRG_CDSITX_MODE_AL_TX_CDSITX_MODE_MASK);
    cdsi_write(dev, CDSI0_AL_TX_BRG_SOFT_RESET_OFFS, 1);
    cdsi_write(dev, CDSI0_AL_TX_BRG_SYSCLK_ENABLE_OFFS, 1);
    cdsi_write(dev, CDSI0_AL_TX_BRG_ENABLE_OFFS, 1);

    /* Tx bridge setting */
    cdsi_write(dev, CDSI0_AL_TX_BRG_MODE_OFFS,
               CDSI0_AL_TX_BRG_MODE_AL_TX_BRG_WAIT_INTERVAL_MODE_MASK |
               CDSI0_AL_TX_BRG_MODE_AL_TX_BRG_MASTER_SYNC_MODE_MASK |
               CDSI0_AL_TX_BRG_MODE_AL_TX_BRG_CSI_MODE_MASK);

    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_COM_SET_OFFS,
               (1 << CDSI0_AL_TX_BRG_PIC_COM_SET_AL_TX_BRG_REG_COM_3D_EN_A_SHIFT) |
               CDSI0_AL_TX_BRG_PIC_COM_SET_AL_TX_BRG_REG_COM_PLURALIMGTYPE_A_MASK |
               CDSI0_AL_TX_BRG_PIC_COM_SET_AL_TX_BRG_REG_COM_FRAMENUM_EN_A_MASK |
               CDSI0_AL_TX_BRG_PIC_COM_SET_AL_TX_BRG_REG_COM_UPDATE_EN_A_MASK);
    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_COM_VDELAYSTRCOUNT_OFFS, 1702);
    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_COM_VDELAYENDCOUNT_OFFS, 1702);
    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_COM_MAXFCNT_OFFS, 0);

    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_SYN_SET_OFFS,
               CDSI0_AL_TX_BRG_PIC_SYN_SET_AL_TX_BRG_REG_SYN_UPDATE_EN_A_MASK);
    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_SYN_LINE_OFFS, 0);

    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_COM_3DCM_PLDT_OFFS, 0);
    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_COM_3DCM_LINE_OFFS, 0);

    cdsi_write(dev, CDSI0_AL_TX_BRG_WAIT_CYCLE_SET_OFFS,
               (16 << CDSI0_AL_TX_BRG_WAIT_CYCLE_SET_AL_TX_BRG_TIM_WAIT_CYCLE_SHIFT) |
               (16 << CDSI0_AL_TX_BRG_WAIT_CYCLE_SET_AL_TX_BRG_IMAGE_WAIT_CYCLE_SHIFT));
    cdsi_write(dev, CDSI0_AL_TX_BRG_VSYNC_LINE_SET_OFFS, 1);
    cdsi_write(dev, CDSI0_AL_TX_BRG_TYPE_SEL1_SET_OFFS, 0x08fbfffc);
    cdsi_write(dev, CDSI0_AL_TX_BRG_TYPE_SEL2_SET_OFFS, 0xff00c0e0);
    cdsi_write(dev, CDSI0_AL_TX_BRG_TYPE_MASK1_SET_OFFS, 0x08fb00fc);
    cdsi_write(dev, CDSI0_AL_TX_BRG_TYPE_MASK2_SET_OFFS, 0xff00c0e0);
    cdsi_write(dev, CDSI0_AL_TX_BRG_STATUS_ENABLE_OFFS,
               0x80 | CDSI0_AL_TX_BRG_STATUS_ENABLE_AL_TX_PKTIF_BUSY_START_ENA_MASK |
               CDSI0_AL_TX_BRG_STATUS_ENABLE_AL_TX_VS_AUTOINS_EXEC_INFO_ENA_MASK |
               CDSI0_AL_TX_BRG_STATUS_ENABLE_AL_TX_HS_AUTOINS_EXEC_INFO_ENA_MASK |
               CDSI0_AL_TX_BRG_STATUS_ENABLE_AL_TX_BRG_WC_ERROR_ENA_MASK |
               CDSI0_AL_TX_BRG_STATUS_ENABLE_AL_TX_BRG_SP_NOEOM_2ND_ERROR_ENA_MASK |
               CDSI0_AL_TX_BRG_STATUS_ENABLE_AL_TX_BRG_EOM_1ST_ERROR_ENA_MASK |
               CDSI0_AL_TX_BRG_STATUS_ENABLE_AL_TX_BRG_FIFO_OVERFLOW_ENA_MASK);
    cdsi_write(dev, CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_OFFS,
               (7 << CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_AL_TX_BRG_UNIPRO_BYTESWAP_BYTE7_SHIFT) |
               (6 << CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_AL_TX_BRG_UNIPRO_BYTESWAP_BYTE6_SHIFT) |
               (5 << CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_AL_TX_BRG_UNIPRO_BYTESWAP_BYTE5_SHIFT) |
               (4 << CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_AL_TX_BRG_UNIPRO_BYTESWAP_BYTE4_SHIFT) |
               (3 << CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_AL_TX_BRG_UNIPRO_BYTESWAP_BYTE3_SHIFT) |
               (2 << CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_AL_TX_BRG_UNIPRO_BYTESWAP_BYTE2_SHIFT) |
               (1 << CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_AL_TX_BRG_UNIPRO_BYTESWAP_BYTE1_SHIFT) |
               (0 << CDSI0_AL_TX_BRG_UNIPRO_BYTESWAP_AL_TX_BRG_UNIPRO_BYTESWAP_BYTE0_SHIFT));

    /* Tx bridge enable */
    cdsi_write(dev, CDSI0_AL_TX_BRG_MODE_OFFS,
               CDSI0_AL_TX_BRG_MODE_AL_TX_BRG_WAIT_INTERVAL_MODE_MASK |
               CDSI0_AL_TX_BRG_MODE_AL_TX_BRG_MASTER_SYNC_MODE_MASK |
               CDSI0_AL_TX_BRG_MODE_AL_TX_BRG_CSI_MODE_MASK |
               CDSI0_AL_TX_BRG_MODE_AL_TX_BRG_EN_MASK);

    /* CDSITX setting */
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_00_OFFS,
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_00_SBS_DPHY_LOCKUPDONE_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_00_SBS_DPHY_AUTOCALDONE_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_00_SBS_DPHY_HSTXVREGRDY_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_00_SBS_DPHY_LINEINITDONE_EN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_01_OFFS,
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_01_SBS_DPHY_ERRFALSECONTROL_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_01_SBS_DPHY_ERRSYNCESC_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_01_SBS_DPHY_ERRESC_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_01_SBS_DPHY_RXTRIGGERESC_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_01_SBS_DPHY_DIRECTION_TX_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_01_SBS_DPHY_DIRECTION_RX_EN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_OFFS,
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRX_CONT_ERR_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRX_ERRWC_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRX_ERRVCID_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRX_ERRDATATYPE_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRX_ERRECCDBL_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRX_ERRECCSINGLE_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRX_CHKSUMERR_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_PRESP_TO_ERR_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_PR_TO_ERR_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_TA_TO_ERR_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRX_TO_ERR_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_HS_TO_ERR_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_PRESP_TO_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_PR_TO_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_TA_TO_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_LPRXH_TO_EN_MASK |
               CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_02_SBS_LINK_HS_TO_EN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_FUNC_ENABLE_03_OFFS, 0);

    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_MASK_00_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_STATUS_00_OFFS, 0xffffffff);

    cdsi_write(dev, CDSI0_CDSITX_POWER_SW_OFFS,
               CDSI0_CDSITX_POWER_SW_SBD_DPHY_COM_EN_ZEMIPIV12_MASK |
               CDSI0_CDSITX_POWER_SW_SBD_DPHY_COM_V12PEN_MASK |
               CDSI0_CDSITX_POWER_SW_SBD_DPHY_COM_V12EN_MASK);

    /* D-PHY reset deassertion */
    cdsi_write(dev, CDSI0_CDSITX_DPHY_RESET_OFFS,
               CDSI0_CDSITX_DPHY_RESET_DPHY_RESET_N_MASK);

    /* D-PHY PLL setting */
    cdsi_write(dev, CDSI0_CDSITX_PLL_CONFIG_00_OFFS,
               (2 << CDSI0_CDSITX_PLL_CONFIG_00_SBS_DPHY_MPM_PRD_SHIFT) |
               (2 << CDSI0_CDSITX_PLL_CONFIG_00_SBS_DPHY_MPM_LBWS_SHIFT) |
               CDSI0_CDSITX_PLL_CONFIG_00_SBS_DPHY_CLM_LFBREN_MASK |
               (124 << CDSI0_CDSITX_PLL_CONFIG_00_SBS_DPHY_MPM_FBD_SHIFT));
    cdsi_write(dev, CDSI0_CDSITX_PLL_CONFIG_02_OFFS, 5760);

    /* D-PHY PLL enable */
    cdsi_write(dev, CDSI0_CDSITX_PLL_CONTROL_00_OFFS,
               CDSI0_CDSITX_PLL_CONTROL_00_SBD_DPHY_MPM_PLLPSEN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_PLL_CONTROL_01_OFFS,
               CDSI0_CDSITX_PLL_CONTROL_01_SBD_DPHY_MP_ENABLE_MASK);

    /* CDSITX setting */
    cdsi_write(dev, CDSI0_CDSITX_LANE_ENABLE_00_OFFS,
               CDSI0_CDSITX_LANE_ENABLE_00_SBS_DPHY_CLM_HM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_00_SBS_DPHY_D3M_HM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_00_SBS_DPHY_D2M_HM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_00_SBS_DPHY_D1M_HM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_00_SBS_DPHY_D0M_HM_EN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_LANE_ENABLE_01_OFFS,
               CDSI0_CDSITX_LANE_ENABLE_01_SBD_DPHY_CLM_SM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_01_SBD_DPHY_D3M_SM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_01_SBD_DPHY_D2M_SM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_01_SBD_DPHY_D1M_SM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_01_SBD_DPHY_D0M_SM_EN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_LANE_ENABLE_02_OFFS,
               CDSI0_CDSITX_LANE_ENABLE_02_SBS_LINK_CLM_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_02_SBS_LINK_D3M_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_02_SBS_LINK_D2M_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_02_SBS_LINK_D1M_EN_MASK |
               CDSI0_CDSITX_LANE_ENABLE_02_SBS_LINK_D0M_EN_MASK);

    /* D-PHY Vreg setting */
    cdsi_write(dev, CDSI0_CDSITX_VREG_CONFIG_OFFS, 19);

    /* D-PHY Vreg enable */
    cdsi_write(dev, CDSI0_CDSITX_VREG_CONTROL_OFFS,
               CDSI0_CDSITX_VREG_CONTROL_SBS_DPHY_CLM_HSTXVREGEN_MASK |
               CDSI0_CDSITX_VREG_CONTROL_SBS_DPHY_D3M_HSTXVREGEN_MASK |
               CDSI0_CDSITX_VREG_CONTROL_SBS_DPHY_D2M_HSTXVREGEN_MASK |
               CDSI0_CDSITX_VREG_CONTROL_SBS_DPHY_D1M_HSTXVREGEN_MASK |
               CDSI0_CDSITX_VREG_CONTROL_SBS_DPHY_D0M_HSTXVREGEN_MASK);

    cdsi_write(dev, CDSI0_CDSITX_LPRX_CALIB_CONFIG_OFFS, 10);
    cdsi_write(dev, CDSI0_CDSITX_LPRX_CALIB_CONTROL_OFFS,
               CDSI0_CDSITX_LPRX_CALIB_CONTROL_SBD_DPHY_CALIB_START_MASK);

    /* CDSITX setting */
    cdsi_write(dev, CDSI0_CDSITX_CSI2DSI_SELECT_OFFS,
               CDSI0_CDSITX_CSI2DSI_SELECT_SBS_APF_CSI2_MODE_MASK |
               CDSI0_CDSITX_CSI2DSI_SELECT_SBS_LINK_CSI2_MODE_MASK);

    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_00_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_01_OFFS,
               CDSI0_CDSITX_GLOBAL_TIMING_PARAM_01_SBS_DPHY_CLM_LPTXCURR1EN_MASK |
               CDSI0_CDSITX_GLOBAL_TIMING_PARAM_01_SBS_DPHY_D3M_LPTXCURR1EN_MASK |
               CDSI0_CDSITX_GLOBAL_TIMING_PARAM_01_SBS_DPHY_D2M_LPTXCURR1EN_MASK |
               CDSI0_CDSITX_GLOBAL_TIMING_PARAM_01_SBS_DPHY_D1M_LPTXCURR1EN_MASK |
               CDSI0_CDSITX_GLOBAL_TIMING_PARAM_01_SBS_DPHY_D0M_LPTXCURR1EN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_02_OFFS,
               6 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_02_SBS_DPHY_HSTXCLK_DIVCNT_SHIFT);
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_03_OFFS,
               6 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_03_SBS_DPHY_PPI_LPTXTIMECNT_SHIFT);
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_04_OFFS,
               (29 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_04_SBS_DPHY_PPI_TCLK_PREZEROCNT_SHIFT) |
               (0 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_04_SBS_DPHY_PPI_TCLK_PRECNT_SHIFT) |
               (7 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_04_SBS_DPHY_PPI_TCLK_PREPARECNT_SHIFT));
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_05_OFFS,
               (14 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_05_SBS_DPHY_PPI_TCLK_EXITCNT_SHIFT) |
               (4 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_05_SBS_DPHY_PPI_TCLK_TRAILCNT_SHIFT));
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_06_OFFS,
               (10 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_06_SBS_DPHY_PPI_THS_PREZEROCNT_SHIFT) |
               (8 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_06_SBS_DPHY_PPI_THS_PREPARECNT_SHIFT));
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_07_OFFS,
               (15 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_07_SBS_DPHY_PPI_THS_EXITCNT_SHIFT) |
               (7 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_07_SBS_DPHY_PPI_THS_TRAILCNT_SHIFT));
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_08_OFFS,
               7967 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_08_SBS_DPHY_PPI_TWAKEUPCNT_SHIFT);
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_09_OFFS,
               16 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_09_SBS_DPHY_PPI_TCLK_POSTCNT_SHIFT);
    cdsi_write(dev, CDSI0_CDSITX_GLOBAL_TIMING_PARAM_10_OFFS,
               (6 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_10_SBS_DPHY_PPI_TXTAGOCNT_SHIFT) |
               (13 << CDSI0_CDSITX_GLOBAL_TIMING_PARAM_10_SBS_DPHY_PPI_RXTASURECNT_SHIFT));

    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_00_OFFS, 1940);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_01_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_02_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_03_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_04_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_05_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_06_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_07_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_08_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_09_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_10_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_COUNT_CONFIG_11_OFFS, 0xffffffff);

    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_00_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_01_OFFS,
               CDSI0_CDSITX_SIDEBAND_CONFIG_01_SBS_DPHY_CLM_LPRXVTHLOW_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_01_SBS_DPHY_D3M_LPRXVTHLOW_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_01_SBS_DPHY_D2M_LPRXVTHLOW_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_01_SBS_DPHY_D1M_LPRXVTHLOW_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_01_SBS_DPHY_D0M_LPRXVTHLOW_MASK);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_02_OFFS,
               CDSI0_CDSITX_SIDEBAND_CONFIG_02_SBS_DPHY_CLM_CAP1_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_02_SBS_DPHY_D3M_CAP1_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_02_SBS_DPHY_D2M_CAP1_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_02_SBS_DPHY_D1M_CAP1_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_02_SBS_DPHY_D0M_CAP1_MASK);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_03_OFFS,
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_CLM_LPTXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D3M_LPTXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D2M_LPTXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D1M_LPTXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D0M_LPTXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_CLM_LPCDTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_CLM_LPRXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D3M_LPCDTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D3M_LPRXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D2M_LPCDTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D2M_LPRXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D1M_LPCDTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D1M_LPRXTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D0M_LPCDTRM_SHIFT) |
               (1 << CDSI0_CDSITX_SIDEBAND_CONFIG_03_SBS_DPHY_D0M_LPRXTRM_SHIFT));
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_04_OFFS,
               (2 << CDSI0_CDSITX_SIDEBAND_CONFIG_04_SBS_DPHY_CLM_HSTXTRM_SHIFT) |
               (2 << CDSI0_CDSITX_SIDEBAND_CONFIG_04_SBS_DPHY_D3M_HSTXTRM_SHIFT) |
               (2 << CDSI0_CDSITX_SIDEBAND_CONFIG_04_SBS_DPHY_D2M_HSTXTRM_SHIFT) |
               (2 << CDSI0_CDSITX_SIDEBAND_CONFIG_04_SBS_DPHY_D1M_HSTXTRM_SHIFT) |
               (2 << CDSI0_CDSITX_SIDEBAND_CONFIG_04_SBS_DPHY_D0M_HSTXTRM_SHIFT));

    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_05_OFFS,
               CDSI0_CDSITX_SIDEBAND_CONFIG_05_SBS_LINK_RXVC3EN_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_05_SBS_LINK_RXVC2EN_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_05_SBS_LINK_RXVC1EN_MASK |
               CDSI0_CDSITX_SIDEBAND_CONFIG_05_SBS_LINK_RXVC0EN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_06_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_07_OFFS, 0);

    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_08_OFFS,
               CDSI0_CDSITX_SIDEBAND_CONFIG_08_SBS_APF_DSI_DTVALID_POL_MASK);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_09_OFFS,
               CDSI0_CDSITX_SIDEBAND_CONFIG_09_SBS_APF_DSI_SYNC_MODE_MASK);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_10_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_11_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_12_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_13_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_14_OFFS, 0);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_CONFIG_15_OFFS, 6144);


    /* Wait PLL lockup time */
    rdata = cdsi_read(dev, CDSI0_CDSITX_INTERRUPT_STATUS_00_OFFS);
    while((rdata &
           CDSI0_CDSITX_INTERRUPT_STATUS_00_INT_DPHY_LOCKUPDONE_MASK) == 0x0) {
        rdata = cdsi_read(dev, CDSI0_CDSITX_INTERRUPT_STATUS_00_OFFS);
    }

    /* Wait D-PHY Vreg startup */
    while((rdata &
           CDSI0_CDSITX_INTERRUPT_STATUS_00_INT_DPHY_HSTXVREGRDY_MASK) == 0x0) {
        rdata = cdsi_read(dev, CDSI0_CDSITX_INTERRUPT_STATUS_00_OFFS);
    }


    cdsi_write(dev, CDSI0_CDSITX_PISO_ENABLE_OFFS,
               CDSI0_CDSITX_PISO_ENABLE_SBS_DPHY_CLM_PISOEN_MASK |
               CDSI0_CDSITX_PISO_ENABLE_SBS_DPHY_D1M_PISOEN_MASK |
               CDSI0_CDSITX_PISO_ENABLE_SBS_DPHY_D0M_PISOEN_MASK);

    /* CDSITX setting */
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_00_OFFS,
               CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_00_SBD_DPHY_MPM_CKEN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_01_OFFS,
               CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_01_SBD_DPHY_MPM_PLLINTCKEN_MASK);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_02_OFFS,
               CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_02_SBD_DPHY_HSTXCLKENABLE_MASK);
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_03_OFFS,
               CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_03_SBD_DPHY_STARTPPI_MASK);

    /* Wait D-PHY line initialization */
    while ((rdata &
            CDSI0_CDSITX_INTERRUPT_STATUS_00_INT_DPHY_LINEINITDONE_MASK) ==
           0x0) {
        rdata = cdsi_read(dev, CDSI0_CDSITX_INTERRUPT_STATUS_00_OFFS);
    }

    /* Clear all interrupt statuses */
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_STATUS_00_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_STATUS_01_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_STATUS_02_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_STATUS_03_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_STATUS_04_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_STATUS_05_OFFS, 0xffffffff);
    cdsi_write(dev, CDSI0_CDSITX_INTERRUPT_STATUS_06_OFFS, 0xffffffff);

    /* Reset deassertion for LINK */
    cdsi_write(dev, CDSI0_CDSITX_LINK_RESET_OFFS,
               CDSI0_CDSITX_LINK_RESET_LINK_RESET_N_MASK);
    /* Reset deassertion for APF */
    cdsi_write(dev, CDSI0_CDSITX_APF_RESET_OFFS,
               CDSI0_CDSITX_APF_RESET_APF_RESET_N_MASK);

    /* APF start */
    cdsi_write(dev, CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_04_OFFS,
               CDSI0_CDSITX_SIDEBAND_INIT_CONTROL_04_SBD_APF_CDSITX_START_MASK);

    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_COM_SET_OFFS,
               (1 << CDSI0_AL_TX_BRG_PIC_COM_SET_AL_TX_BRG_REG_COM_3D_EN_A_SHIFT) |
               CDSI0_AL_TX_BRG_PIC_COM_SET_AL_TX_BRG_REG_COM_FRAMENUM_EN_A_MASK |
               CDSI0_AL_TX_BRG_PIC_COM_SET_AL_TX_BRG_REG_COM_UPDATE_EN_A_MASK);
    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_SYN_SET_OFFS,
               CDSI0_AL_TX_BRG_PIC_SYN_SET_AL_TX_BRG_REG_SYN_UPDATE_EN_A_MASK);
    cdsi_write(dev, CDSI0_AL_TX_BRG_VPARAM_UPDATE_OFFS,
               CDSI0_AL_TX_BRG_VPARAM_UPDATE_AL_TX_BRG_SYS_UPDATE_EN_MASK |
               CDSI0_AL_TX_BRG_VPARAM_UPDATE_AL_TX_BRG_COM_UPDATE_EN_MASK);
    cdsi_write(dev, CDSI0_AL_TX_BRG_PIC_COM_START_OFFS,
               CDSI0_AL_TX_BRG_PIC_COM_START_AL_TX_BRG_REG_COM_START_A_MASK);

    return 0;
}

/**
 * @brief Set the registers in CSI controller to stop transfer.
 * @param dev Pointer to the CDSI device
 *
 * @return 0 on success or a negative error code on failure.
 */
int csi_tx_stop(struct cdsi_dev *dev)
{
    /* Stop the Pixel I/F of CDSITX */

    /* Wait the stop of Pixel I/F */

    /* Wait until the transmission from UniPro to CDSITX is stopped */

    /* Disable the Tx bridge */

    /* Assert the Tx bridge reset */

    /* Stop the APF function */

    /* Disable the PPI function */

    /* Disable the clock distribution for LINK and APF */

    /* Assert the APF reset */

    /* Assert the LINK reset */

    /* Initialize the PPI */

    /* Enable the clock distribution to stop the clock lane of D-PHY */

    /* Wait for stop the clock lane of D-PHY */

    /* Disable the clock destribuiton to stop the clock lane of D-PHY */

    /* Disable the voltage requlator for D-PHY */

    /* Disable D-PHY functions */

    /* Disable PLL for CDSI */

    /* Clear the interrupt statuses */

    /* Release the Initialization signal for the PPI */

    return 0;
}
